export const headers = [
  {
    key: "external_id",
    label: "External ID",
  },
  {
    key: "id",
    label: "ID",
  },
  {
    key: "date_created",
    label: "Date created",
  },
  {
    key: "date_finished",
    label: "Date finished",
  },
  {
    key: "processing_currency",
    label: "Processing Currency",
  },
  {
    key: "processing_amount",
    label: "Processing Amount",
  },
  {
    key: "user_currency",
    label: "User Currency",
  },
  {
    key: "user_amount",
    label: "User Amount",
  },
  {
    key: "type",
    label: "Type",
  },
  {
    key: "status",
    label: "Status",
  },
  {
    key: "card",
    label: "Card",
  },
  {
    key: "payment_method",
    label: "Payment Method",
  },
  {
    key: "user_category",
    label: "User category",
  },
  {
    key: "payment_group",
    label: "Payment group",
  },
  {
    key: "gate",
    label: "Gate",
  },
  {
    key: "payment_system",
    label: "Payment system",
  },
  {
    key: "order_id",
    label: "Order ID",
  },
  {
    key: "customer_method",
    label: "Customer Method",
  },
  {
    key: "user_id",
    label: "User ID (site_login)",
  },
  {
    key: "country",
    label: "User country",
  },
];
export const items = [
  {
    external_id: 56874568,
    id: 4643546,
    date_created: "2012-05-22",
    date_finished: "2012-05-23",
    processing_currency: "EUR",
    processing_amount: 505.9,
    user_currency: "EUR",
    user_amount: 505.9,
    type: "Deposit",
    status: "Success",
    card: "Visa 5465",
    payment_method: "VISA",
    user_category: "Default",
    payment_group: "Group name",
    gate: "Gate name",
    payment_system: "Casino 888",
    order_id: 9058395,
    customer_method: 8459438584,
    user_id: "589686858484545",
    country: "Montserrat",
  },
  {
    external_id: 5968475,
    id: 9058395,
    date_created: "2022-01-24",
    date_finished: "2022-08-07",
    processing_currency: "EUR",
    processing_amount: 989.48,
    user_currency: "EUR",
    user_amount: 989.48,
    type: "Payout",
    status: "Decline",
    card: "MC 1236",
    payment_method: "MC",
    user_category: "Japan_Trusted",
    payment_group: "Group name",
    gate: "Gate name",
    payment_system: "Super Casino",
    order_id: 4643546,
    customer_method: 74583928748,
    user_id: "johnwick@gmail.com",
    country: "Aruba",
  },
  {
    external_id: 34618475,
    id: 34513455,
    date_created: "2022-04-04",
    date_finished: "2022-08-07",
    processing_currency: "EUR",
    processing_amount: 989.48,
    user_currency: "EUR",
    user_amount: 989.48,
    type: "Refund",
    status: "Processing",
    card: "MC 1236",
    payment_method: "MC",
    user_category: "Japan_Trusted",
    payment_group: "Group name",
    gate: "Gate name",
    payment_system: "Super Casino",
    order_id: 4643546,
    customer_method: 74583928748,
    user_id: "johnwick@gmail.com",
    country: "Aruba",
  },
  {
    external_id: 34628475,
    id: 34532455,
    date_created: "2022-04-04",
    date_finished: "2022-08-07",
    processing_currency: "EUR",
    processing_amount: 989.48,
    user_currency: "EUR",
    user_amount: 989.48,
    type: "Deposit",
    status: "Success",
    card: "MC 1236",
    payment_method: "MC",
    user_category: "Japan_Trusted",
    payment_group: "Group name",
    gate: "Gate name",
    payment_system: "Super Casino",
    order_id: 4643546,
    customer_method: 74583928748,
    user_id: "johnwick@gmail.com",
    country: "Aruba",
  },
  {
    external_id: 34638475,
    id: 34533455,
    date_created: "2022-04-04",
    date_finished: "2022-08-07",
    processing_currency: "EUR",
    processing_amount: 989.48,
    user_currency: "EUR",
    user_amount: 989.48,
    type: "Payout",
    status: "Success",
    card: "MC 1236",
    payment_method: "VISA",
    user_category: "Japan_Trusted",
    payment_group: "Group name",
    gate: "Gate name",
    payment_system: "Super Casino",
    order_id: 4643546,
    customer_method: 74583928748,
    user_id: "johnwick@gmail.com",
    country: "Aruba",
  },
];
